# These are the ways users can support this project.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [srmcguirt]
custom: ["https://srmcguirt.gumroad.com"]
